sudo: false
language: python
branches:
  only:
  - pelican
before_install:
- openssl aes-256-cbc -K $encrypted_d4a151962317_key -iv $encrypted_d4a151962317_iv
  -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git --version
- git remote set-url origin git@github.com:pythonbrasil/pythonbrasil.github.io.git
- git fetch origin -f master:master
install:
- pip install -r requirements.txt
script:
- make html
deploy:
  provider: script
  script: make travis ping
  on:
    branch: pelican
    condition: $TRAVIS_PULL_REQUEST = false
